### ISSUE TITLE
[Bug] Magnifying window while drawing (iPad Safari)

### ISSUE THREAD

**Issue by tamagoez** [tamagoez/cokia-web#1]
Found on iPad OS 15.6 and also iPad OS 16.3<=.
While drawing, it shows small magnifying window sometimes.
It is a little annoying.

**Comment by tamagoez** [comment]
Tried
```css
-ms-touch-action: none;
touch-action: none;
user-select: none;
-moz-user-select: none;
-webkit-user-select: none;
-webkit-touch-callout: none;
-webkit-user-drag: none; 
```
But it didn't work.

Also
```typescript
<div onTouchStart={(e) => e.preventDefault()}>{children}</div>
```

**Comment by tamagoez** [comment]
Priority mistake?
A new CSS generated by Autoprefixer.

```css

/*
* Prefixed by https://autoprefixer.github.io
* PostCSS: v8.4.14,
* Autoprefixer: v10.4.7
* Browsers: defaults
*/

.example {
    -webkit-user-select: none;
       -moz-user-select: none;
            user-select: none;
    touch-action: none;
    -webkit-touch-callout: none;
    -webkit-user-drag: none; 
}
```
